platform :ios, '15.0'

target 'genui_ios' do
  use_frameworks! :linkage => :static
  pod 'A2UI', :path => '../A2UI'

  target 'A2UITests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
    end
  end
end
